config/routes.rb
MultipleSourceUse::Application.routes.draw do
  root :to => 'pages#welcome'
  get '/goodbye'  => 'pages#goodbye'

  resources :participants, :except => [:edit, :update]
  get '/directions' => 'pages#directions'
  get '/task_analysis' => 'pages#task_analysis'
  post '/task_analysis' => 'pages#update_task_analysis'
  get '/library'    => 'pages#library'
  resources :stances
  get '/ranking'    => 'pages#ranking'
  resources :rankings

  get "/dashboard" => 'dashboard#index'
  get "dashboard/participants"
  get "dashboard/rankings"
  get "dashboard/sources"
  get "dashboard/stances"

end

app/models/ranking.rb
# == Schema Information
# Schema version: 20140320051046
#
# Table name: rankings
#
#  id                        :integer          not null, primary key
#  stance_id                 :integer
#  source_name               :string
#  category                  :integer
#  useful_ranking            :integer
#  useful_justification      :string
#  trustworthy_ranking       :integer
#  trustworthy_justification :string
#  accurate_ranking          :integer
#  accurate_justification    :string
#  interesting_ranking       :integer
#  interesting_justification :string
#  created_at                :datetime
#  updated_at                :datetime
#
# Indexes
#
#  index_rankings_on_stance_id  (stance_id)
#

class Ranking < ActiveRecord::Base
	belongs_to :stance, :class_name => "Stance", :foreign_key => "stance_id"
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_ranking, only: [:show, :edit, :update, :destroy]

  # GET /rankings
  # GET /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1
  # GET /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
  end

  # POST /rankings
  # POST /rankings.json
  def create
    @ranking = Ranking.new(ranking_params)

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, notice: 'Ranking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ranking }
      else
        format.html { render action: 'new' }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1
  # PATCH/PUT /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to @ranking, notice: 'Ranking was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @ranking }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.json
  def destroy
    @ranking.destroy
    respond_to do |format|
      format.html { redirect_to rankings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranking_params
      params.require(:ranking).permit(:stance_id, :category, :useful_ranking, :useful_justification, :trustworthy_ranking, :trustworthy_justification, :accurate_ranking, :accurate_justification, :interesting_ranking, :interesting_justification)
    end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stance_id %><br>
    <%= f.number_field :stance_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.label :useful_ranking %><br>
    <%= f.number_field :useful_ranking %>
  </div>
  <div class="field">
    <%= f.label :useful_justification %><br>
    <%= f.text_field :useful_justification %>
  </div>
  <div class="field">
    <%= f.label :trustworthy_ranking %><br>
    <%= f.number_field :trustworthy_ranking %>
  </div>
  <div class="field">
    <%= f.label :trustworthy_justification %><br>
    <%= f.text_field :trustworthy_justification %>
  </div>
  <div class="field">
    <%= f.label :accurate_ranking %><br>
    <%= f.number_field :accurate_ranking %>
  </div>
  <div class="field">
    <%= f.label :accurate_justification %><br>
    <%= f.text_field :accurate_justification %>
  </div>
  <div class="field">
    <%= f.label :interesting_ranking %><br>
    <%= f.number_field :interesting_ranking %>
  </div>
  <div class="field">
    <%= f.label :interesting_justification %><br>
    <%= f.text_field :interesting_justification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <thead>
    <tr>
      <th>Stance</th>
      <th>Category</th>
      <th>Useful ranking</th>
      <th>Useful justification</th>
      <th>Trustworthy ranking</th>
      <th>Trustworthy justification</th>
      <th>Accurate ranking</th>
      <th>Accurate justification</th>
      <th>Interesting ranking</th>
      <th>Interesting justification</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
      <tr>
        <td><%= ranking.stance_id %></td>
        <td><%= ranking.category %></td>
        <td><%= ranking.useful_ranking %></td>
        <td><%= ranking.useful_justification %></td>
        <td><%= ranking.trustworthy_ranking %></td>
        <td><%= ranking.trustworthy_justification %></td>
        <td><%= ranking.accurate_ranking %></td>
        <td><%= ranking.accurate_justification %></td>
        <td><%= ranking.interesting_ranking %></td>
        <td><%= ranking.interesting_justification %></td>
        <td><%= link_to 'Show', ranking %></td>
        <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
        <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stance:</strong>
  <%= @ranking.stance_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @ranking.category %>
</p>

<p>
  <strong>Useful ranking:</strong>
  <%= @ranking.useful_ranking %>
</p>

<p>
  <strong>Useful justification:</strong>
  <%= @ranking.useful_justification %>
</p>

<p>
  <strong>Trustworthy ranking:</strong>
  <%= @ranking.trustworthy_ranking %>
</p>

<p>
  <strong>Trustworthy justification:</strong>
  <%= @ranking.trustworthy_justification %>
</p>

<p>
  <strong>Accurate ranking:</strong>
  <%= @ranking.accurate_ranking %>
</p>

<p>
  <strong>Accurate justification:</strong>
  <%= @ranking.accurate_justification %>
</p>

<p>
  <strong>Interesting ranking:</strong>
  <%= @ranking.interesting_ranking %>
</p>

<p>
  <strong>Interesting justification:</strong>
  <%= @ranking.interesting_justification %>
</p>

<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>