config/routes.rb
MultipleSourceUse::Application.routes.draw do
  root :to => 'pages#welcome'
  get '/goodbye'  => 'pages#goodbye'

  resources :participants, :except => [:edit, :update]
  get '/directions' => 'pages#directions'
  get '/task_analysis' => 'pages#task_analysis'
  post '/task_analysis' => 'pages#update_task_analysis'
  get '/library'    => 'pages#library'
  resources :stances
  get '/ranking'    => 'pages#ranking'
  resources :rankings

  get "/dashboard" => 'dashboard#index'
  get "dashboard/participants"
  get "dashboard/rankings"
  get "dashboard/sources"
  get "dashboard/stances"

end

app/models/participant.rb
# == Schema Information
# Schema version: 20140320051046
#
# Table name: participants
#
#  id         :integer          not null, primary key
#  session_id :string
#  ip_address :string
#  first_name :string
#  last_name  :string
#  instructor :string
#  email      :string
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_participants_on_session_id  (session_id)
#

class Participant < ActiveRecord::Base
  validates_presence_of :session_id
  validates_presence_of :ip_address
  
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :instructor
  validates_presence_of :email

  has_one :stance, :dependent => :destroy
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_admin, except: [:new, :create]
  before_action :set_participant, only: [:show, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html
      format.json
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << ["id","ip_address", "first_name", "last_name", "email", "instructor", "session_id", "created_at", "updated_at"]
          @participants.each do |p|
            csv << [p.id, p.ip_address, p.first_name, p.last_name, p.email, p.instructor, p.session_id, p.created_at, p.updated_at]
          end
        end

        send_data csv_string, :type => 'text/csv; charset=iso-8859-1; header=present',
                              :disposition => "attachment; filename=participants.csv"
      }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)
    @participant.session_id = session[:session_id]
    @participant.ip_address = request.ip

    respond_to do |format|
      if @participant.save
        format.html { redirect_to directions_path }
        format.json { render action: 'show', status: :created, location: @participant }
      else
        format.html { render action: 'new' }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:first_name, :last_name, :instructor, :email)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for @participant, :html => { :class => "form" } do |f| %>
  <%= render "shared/error_messages", :object => f.object %>

  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="form-group">
        <%= f.label :first_name, :class => "control-label" %>
        <%= f.text_field :first_name, :class => "form-control" %>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="form-group">
        <%= f.label :last_name, :class => "control-label" %>
        <%= f.text_field :last_name, :class => "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="form-group">
        <%= f.label :course, :class => "control-label" %>
        <%= f.text_field :instructor, :class => "form-control" %>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="form-group">
        <%= f.label :email, :class => "control-label" %>
        <%= f.text_field :email, :class => "form-control" %>
      </div>
    </div>
  </div>


  <div class="actions">
    <%= f.submit "Continue", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/participants/index.html.erb
<h1 class="no-top">Listing participants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Session</th>
      <th>Ip address</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Instructor</th>
      <th>Email</th>
      <th>Created At</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.id %></td>
        <td><%= participant.session_id %></td>
        <td><%= participant.ip_address %></td>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= participant.instructor %></td>
        <td><%= participant.email %></td>
        <td><%= participant.created_at %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path, :class => "btn btn-default" %>

app/views/participants/new.html.erb
<br>

<table class="table table-bordered table-striped">
  <tbody>

  </tbody>
</table>

<%= render 'form' %>

app/views/participants/show.html.erb
<p>
  <strong>Session:</strong>
  <%= @participant.session_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @participant.ip_address %>
</p>

<p>
  <strong>First name:</strong>
  <%= @participant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @participant.last_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @participant.instructor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<%= link_to 'Back', participants_path %>