config/routes.rb
MultipleSourceUse::Application.routes.draw do
  root :to => 'pages#welcome'
  get '/goodbye'  => 'pages#goodbye'

  resources :participants, :except => [:edit, :update]
  get '/directions' => 'pages#directions'
  get '/task_analysis' => 'pages#task_analysis'
  post '/task_analysis' => 'pages#update_task_analysis'
  get '/library'    => 'pages#library'
  resources :stances
  get '/ranking'    => 'pages#ranking'
  resources :rankings

  get "/dashboard" => 'dashboard#index'
  get "dashboard/participants"
  get "dashboard/rankings"
  get "dashboard/sources"
  get "dashboard/stances"

end

app/models/stance.rb
# == Schema Information
# Schema version: 20140320051046
#
# Table name: stances
#
#  id             :integer          not null, primary key
#  participant_id :integer
#  supporting     :integer
#  created_at     :datetime
#  updated_at     :datetime
#  statement      :text
#
# Indexes
#
#  index_stances_on_participant_id  (participant_id)
#

class Stance < ActiveRecord::Base
	validates_presence_of :participant_id

	belongs_to :participant, :class_name => "Participant", :foreign_key => "participant_id"
	has_many :sources, :class_name => "Source", :foreign_key => "stance_id", :dependent => :destroy
	has_many :rankings, :class_name => "Ranking", :foreign_key => "stance_id", :dependent => :destroy

	accepts_nested_attributes_for :sources
	accepts_nested_attributes_for :rankings
end

app/controllers/stances_controller.rb
class StancesController < ApplicationController
  before_action :authenticate_admin, except: [:create, :update]
  before_action :set_stance, only: [:show, :edit, :update, :destroy]

  # GET /stances
  # GET /stances.json
  def index
    @stances = Stance.all
  end

  # GET /stances/1
  # GET /stances/1.json
  def show
  end

  # GET /stances/new
  def new
    @stance = Stance.new
  end

  # GET /stances/1/edit
  def edit
  end

  # POST /stances
  # POST /stances.json
  def create
    @stance = Stance.new(stance_params)
    @stance.participant = Participant.find_by(:session_id => session[:session_id])

    respond_to do |format|
      if @stance.save
        format.html { redirect_to goodbye_path }
        format.json { render action: 'show', status: :created, location: @stance }
      else
        format.html { render action: 'new' }
        format.json { render json: @stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stances/1
  # PATCH/PUT /stances/1.json
  def update
    respond_to do |format|
      if @stance.update(stance_params)
        format.html { redirect_to goodbye_path }
        format.json { render action: 'show', status: :ok, location: @stance }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stances/1
  # DELETE /stances/1.json
  def destroy
    @stance.destroy
    respond_to do |format|
      format.html { redirect_to stances_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stance
      @stance = Stance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stance_params
      params.require(:stance).permit(:supporting, :statement, :source_order,
        :sources_attributes => [
          :order, :time_duration, :trustworthy, :useful, :accurate, :interesting, :source_name, :depth,
          :pre_reason, :pre_reason_other_text, :like_text, :sentiment, :post_reason, :post_reason_other_text
        ],
        :rankings_attributes => [:source_name, :useful_ranking, :useful_justification,
          :trustworthy_ranking, :trustworthy_justification, :accurate_ranking, :accurate_justification,
          :interesting_ranking, :interesting_justification])
    end
end

app/helpers/stances_helper.rb
module StancesHelper
end

app/views/stances/_form.html.erb
<%= form_for(@stance) do |f| %>
  <%= render "shared/error_messages", :object => f.object %>

  <div class="field">
    <%= f.label :participant_id %><br>
    <%= f.number_field :participant_id %>
  </div>
  <div class="field">
    <%= f.label :supporting %><br>
    <%= f.number_field :supporting %>
  </div>
  <div class="field">
    <%= f.label :statement %><br>
    <%= f.text_area :statement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stances/edit.html.erb
<h1>Editing stance</h1>

<%= render 'form' %>

<%= link_to 'Show', @stance %> |
<%= link_to 'Back', stances_path %>

app/views/stances/index.html.erb
<h1>Listing stances</h1>

<table>
  <thead>
    <tr>
      <th>Participant</th>
      <th>Supporting</th>
      <th>Statement</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stances.each do |stance| %>
      <tr>
        <td><%= stance.participant_id %></td>
        <td><%= stance.supporting %></td>
        <td><%= stance.statement %></td>
        <td><%= link_to 'Show', stance %></td>
        <td><%= link_to 'Edit', edit_stance_path(stance) %></td>
        <td><%= link_to 'Destroy', stance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stance', new_stance_path %>

app/views/stances/new.html.erb
<h1>New stance</h1>

<%= render 'form' %>

<%= link_to 'Back', stances_path %>

app/views/stances/show.html.erb
<p>
  <strong>Participant:</strong>
  <%= @stance.participant_id %>
</p>

<p>
  <strong>Supporting:</strong>
  <%= @stance.supporting %>
</p>

<p>
  <strong>Statement:</strong>
  <%= @stance.statement %>
</p>

<%= link_to 'Edit', edit_stance_path(@stance) %> |
<%= link_to 'Back', stances_path %>